# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-14 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_jjss_mcks_xiencias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Descripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(blank=True, max_length=1000, null=True)),
                ('numero_documento', models.CharField(blank=True, max_length=1000, null=True)),
                ('fecha_emecion', models.CharField(blank=True, max_length=1000, null=True)),
                ('fecha_vencimiento', models.CharField(blank=True, max_length=1000, null=True)),
                ('mes_correspondiente', models.CharField(blank=True, max_length=1000, null=True)),
                ('monto', models.CharField(blank=True, max_length=1000, null=True)),
                ('impuesto', models.CharField(blank=True, max_length=1000, null=True)),
                ('fecha_pago', models.CharField(blank=True, max_length=1000, null=True)),
                ('forma_pago', models.CharField(blank=True, max_length=1000, null=True)),
                ('monto_pagar', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='produccion',
            name='categoria',
            field=models.ForeignKey(blank=True, max_length=1000, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_categoria', to='polls.Tipo'),
        ),
        migrations.AddField(
            model_name='produccion',
            name='descripcion',
            field=models.ForeignKey(blank=True, max_length=1000, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_descripcion', to='polls.Descripcion'),
        ),
        migrations.AddField(
            model_name='produccion',
            name='documento',
            field=models.ForeignKey(blank=True, max_length=1000, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_documento', to='polls.Documento'),
        ),
        migrations.AddField(
            model_name='produccion',
            name='estado_desc',
            field=models.ForeignKey(blank=True, max_length=1000, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_estadodes', to='polls.Documento'),
        ),
        migrations.AddField(
            model_name='produccion',
            name='estado_registro',
            field=models.ForeignKey(blank=True, max_length=1000, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_estadores', to='polls.Documento'),
        ),
        migrations.AddField(
            model_name='produccion',
            name='tipo',
            field=models.ForeignKey(blank=True, max_length=1000, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_tipo', to='polls.Tipo'),
        ),
    ]
